import Head from 'next/head'
import Image from 'next/image'
import { useTheme as useNextTheme } from 'next-themes'
import { Switch, useTheme, Spacer } from '@nextui-org/react'


import styles from '../styles/Home.module.css'


export default function Home() {
  const { setTheme } = useNextTheme();
  const { isDark, type } = useTheme();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bit<a href="https://github.com/BitByBite-xyz">By</a>Bite
        </h1>

        <Spacer />
        <Switch
          checked={isDark}
          onChange={(e) => setTheme(e.target.checked ? 'dark' : 'light')}
        />
        <Spacer />
        <div className={styles.grid}>


          <a href="https://github.com/BitByBite-xyz" className={styles.card}>
            <h2>github &rarr;</h2>
            <p>
              📖📖📖
            </p>
          </a>

          <a
            href="https://github.com/orgs/BitByBite-xyz/people"
            className={styles.card}
          >
            <h2>people &rarr;</h2>
            <p>🧑‍💻🧑‍💻🧑‍💻</p>
          </a>


        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
